name: LICENSE-GENERATOR

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [linux, windows, darwin]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22.3'  

       - name: Build the binary
        run: |
          GOOS=${{ matrix.os }} go build -o license-generator-${{ matrix.os }}

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: 'License Generator Release ${{ github.ref }}'
          body: |
            Initial release of license-generator for ${{ matrix.os }}.
          draft: false
          prerelease: false

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./license-generator-${{ matrix.os }}
          asset_name: license-generator-${{ matrix.os }}
          asset_content_type: application/octet-stream
          token: ${{ secrets.RELEASE_TOKEN }}